// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarms.proto

package org.opennms.integration.api.v1.proto;

public final class Alarms {
  private Alarms() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AlarmsListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oia.AlarmsList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .oia.Alarm alarms = 1;</code>
     */
    java.util.List<org.opennms.integration.api.v1.proto.Model.Alarm> 
        getAlarmsList();
    /**
     * <code>repeated .oia.Alarm alarms = 1;</code>
     */
    org.opennms.integration.api.v1.proto.Model.Alarm getAlarms(int index);
    /**
     * <code>repeated .oia.Alarm alarms = 1;</code>
     */
    int getAlarmsCount();
    /**
     * <code>repeated .oia.Alarm alarms = 1;</code>
     */
    java.util.List<? extends org.opennms.integration.api.v1.proto.Model.AlarmOrBuilder> 
        getAlarmsOrBuilderList();
    /**
     * <code>repeated .oia.Alarm alarms = 1;</code>
     */
    org.opennms.integration.api.v1.proto.Model.AlarmOrBuilder getAlarmsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code oia.AlarmsList}
   */
  public  static final class AlarmsList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oia.AlarmsList)
      AlarmsListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AlarmsList.newBuilder() to construct.
    private AlarmsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AlarmsList() {
      alarms_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AlarmsList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AlarmsList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                alarms_ = new java.util.ArrayList<org.opennms.integration.api.v1.proto.Model.Alarm>();
                mutable_bitField0_ |= 0x00000001;
              }
              alarms_.add(
                  input.readMessage(org.opennms.integration.api.v1.proto.Model.Alarm.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          alarms_ = java.util.Collections.unmodifiableList(alarms_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opennms.integration.api.v1.proto.Alarms.internal_static_oia_AlarmsList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opennms.integration.api.v1.proto.Alarms.internal_static_oia_AlarmsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opennms.integration.api.v1.proto.Alarms.AlarmsList.class, org.opennms.integration.api.v1.proto.Alarms.AlarmsList.Builder.class);
    }

    public static final int ALARMS_FIELD_NUMBER = 1;
    private java.util.List<org.opennms.integration.api.v1.proto.Model.Alarm> alarms_;
    /**
     * <code>repeated .oia.Alarm alarms = 1;</code>
     */
    public java.util.List<org.opennms.integration.api.v1.proto.Model.Alarm> getAlarmsList() {
      return alarms_;
    }
    /**
     * <code>repeated .oia.Alarm alarms = 1;</code>
     */
    public java.util.List<? extends org.opennms.integration.api.v1.proto.Model.AlarmOrBuilder> 
        getAlarmsOrBuilderList() {
      return alarms_;
    }
    /**
     * <code>repeated .oia.Alarm alarms = 1;</code>
     */
    public int getAlarmsCount() {
      return alarms_.size();
    }
    /**
     * <code>repeated .oia.Alarm alarms = 1;</code>
     */
    public org.opennms.integration.api.v1.proto.Model.Alarm getAlarms(int index) {
      return alarms_.get(index);
    }
    /**
     * <code>repeated .oia.Alarm alarms = 1;</code>
     */
    public org.opennms.integration.api.v1.proto.Model.AlarmOrBuilder getAlarmsOrBuilder(
        int index) {
      return alarms_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < alarms_.size(); i++) {
        output.writeMessage(1, alarms_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < alarms_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, alarms_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.opennms.integration.api.v1.proto.Alarms.AlarmsList)) {
        return super.equals(obj);
      }
      org.opennms.integration.api.v1.proto.Alarms.AlarmsList other = (org.opennms.integration.api.v1.proto.Alarms.AlarmsList) obj;

      if (!getAlarmsList()
          .equals(other.getAlarmsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAlarmsCount() > 0) {
        hash = (37 * hash) + ALARMS_FIELD_NUMBER;
        hash = (53 * hash) + getAlarmsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opennms.integration.api.v1.proto.Alarms.AlarmsList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oia.AlarmsList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oia.AlarmsList)
        org.opennms.integration.api.v1.proto.Alarms.AlarmsListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opennms.integration.api.v1.proto.Alarms.internal_static_oia_AlarmsList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opennms.integration.api.v1.proto.Alarms.internal_static_oia_AlarmsList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opennms.integration.api.v1.proto.Alarms.AlarmsList.class, org.opennms.integration.api.v1.proto.Alarms.AlarmsList.Builder.class);
      }

      // Construct using org.opennms.integration.api.v1.proto.Alarms.AlarmsList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAlarmsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (alarmsBuilder_ == null) {
          alarms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          alarmsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opennms.integration.api.v1.proto.Alarms.internal_static_oia_AlarmsList_descriptor;
      }

      @java.lang.Override
      public org.opennms.integration.api.v1.proto.Alarms.AlarmsList getDefaultInstanceForType() {
        return org.opennms.integration.api.v1.proto.Alarms.AlarmsList.getDefaultInstance();
      }

      @java.lang.Override
      public org.opennms.integration.api.v1.proto.Alarms.AlarmsList build() {
        org.opennms.integration.api.v1.proto.Alarms.AlarmsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.opennms.integration.api.v1.proto.Alarms.AlarmsList buildPartial() {
        org.opennms.integration.api.v1.proto.Alarms.AlarmsList result = new org.opennms.integration.api.v1.proto.Alarms.AlarmsList(this);
        int from_bitField0_ = bitField0_;
        if (alarmsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            alarms_ = java.util.Collections.unmodifiableList(alarms_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.alarms_ = alarms_;
        } else {
          result.alarms_ = alarmsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opennms.integration.api.v1.proto.Alarms.AlarmsList) {
          return mergeFrom((org.opennms.integration.api.v1.proto.Alarms.AlarmsList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opennms.integration.api.v1.proto.Alarms.AlarmsList other) {
        if (other == org.opennms.integration.api.v1.proto.Alarms.AlarmsList.getDefaultInstance()) return this;
        if (alarmsBuilder_ == null) {
          if (!other.alarms_.isEmpty()) {
            if (alarms_.isEmpty()) {
              alarms_ = other.alarms_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAlarmsIsMutable();
              alarms_.addAll(other.alarms_);
            }
            onChanged();
          }
        } else {
          if (!other.alarms_.isEmpty()) {
            if (alarmsBuilder_.isEmpty()) {
              alarmsBuilder_.dispose();
              alarmsBuilder_ = null;
              alarms_ = other.alarms_;
              bitField0_ = (bitField0_ & ~0x00000001);
              alarmsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAlarmsFieldBuilder() : null;
            } else {
              alarmsBuilder_.addAllMessages(other.alarms_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opennms.integration.api.v1.proto.Alarms.AlarmsList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opennms.integration.api.v1.proto.Alarms.AlarmsList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.opennms.integration.api.v1.proto.Model.Alarm> alarms_ =
        java.util.Collections.emptyList();
      private void ensureAlarmsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          alarms_ = new java.util.ArrayList<org.opennms.integration.api.v1.proto.Model.Alarm>(alarms_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.opennms.integration.api.v1.proto.Model.Alarm, org.opennms.integration.api.v1.proto.Model.Alarm.Builder, org.opennms.integration.api.v1.proto.Model.AlarmOrBuilder> alarmsBuilder_;

      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public java.util.List<org.opennms.integration.api.v1.proto.Model.Alarm> getAlarmsList() {
        if (alarmsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(alarms_);
        } else {
          return alarmsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public int getAlarmsCount() {
        if (alarmsBuilder_ == null) {
          return alarms_.size();
        } else {
          return alarmsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public org.opennms.integration.api.v1.proto.Model.Alarm getAlarms(int index) {
        if (alarmsBuilder_ == null) {
          return alarms_.get(index);
        } else {
          return alarmsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public Builder setAlarms(
          int index, org.opennms.integration.api.v1.proto.Model.Alarm value) {
        if (alarmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlarmsIsMutable();
          alarms_.set(index, value);
          onChanged();
        } else {
          alarmsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public Builder setAlarms(
          int index, org.opennms.integration.api.v1.proto.Model.Alarm.Builder builderForValue) {
        if (alarmsBuilder_ == null) {
          ensureAlarmsIsMutable();
          alarms_.set(index, builderForValue.build());
          onChanged();
        } else {
          alarmsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public Builder addAlarms(org.opennms.integration.api.v1.proto.Model.Alarm value) {
        if (alarmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlarmsIsMutable();
          alarms_.add(value);
          onChanged();
        } else {
          alarmsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public Builder addAlarms(
          int index, org.opennms.integration.api.v1.proto.Model.Alarm value) {
        if (alarmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlarmsIsMutable();
          alarms_.add(index, value);
          onChanged();
        } else {
          alarmsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public Builder addAlarms(
          org.opennms.integration.api.v1.proto.Model.Alarm.Builder builderForValue) {
        if (alarmsBuilder_ == null) {
          ensureAlarmsIsMutable();
          alarms_.add(builderForValue.build());
          onChanged();
        } else {
          alarmsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public Builder addAlarms(
          int index, org.opennms.integration.api.v1.proto.Model.Alarm.Builder builderForValue) {
        if (alarmsBuilder_ == null) {
          ensureAlarmsIsMutable();
          alarms_.add(index, builderForValue.build());
          onChanged();
        } else {
          alarmsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public Builder addAllAlarms(
          java.lang.Iterable<? extends org.opennms.integration.api.v1.proto.Model.Alarm> values) {
        if (alarmsBuilder_ == null) {
          ensureAlarmsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, alarms_);
          onChanged();
        } else {
          alarmsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public Builder clearAlarms() {
        if (alarmsBuilder_ == null) {
          alarms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          alarmsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public Builder removeAlarms(int index) {
        if (alarmsBuilder_ == null) {
          ensureAlarmsIsMutable();
          alarms_.remove(index);
          onChanged();
        } else {
          alarmsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public org.opennms.integration.api.v1.proto.Model.Alarm.Builder getAlarmsBuilder(
          int index) {
        return getAlarmsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public org.opennms.integration.api.v1.proto.Model.AlarmOrBuilder getAlarmsOrBuilder(
          int index) {
        if (alarmsBuilder_ == null) {
          return alarms_.get(index);  } else {
          return alarmsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public java.util.List<? extends org.opennms.integration.api.v1.proto.Model.AlarmOrBuilder> 
           getAlarmsOrBuilderList() {
        if (alarmsBuilder_ != null) {
          return alarmsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(alarms_);
        }
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public org.opennms.integration.api.v1.proto.Model.Alarm.Builder addAlarmsBuilder() {
        return getAlarmsFieldBuilder().addBuilder(
            org.opennms.integration.api.v1.proto.Model.Alarm.getDefaultInstance());
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public org.opennms.integration.api.v1.proto.Model.Alarm.Builder addAlarmsBuilder(
          int index) {
        return getAlarmsFieldBuilder().addBuilder(
            index, org.opennms.integration.api.v1.proto.Model.Alarm.getDefaultInstance());
      }
      /**
       * <code>repeated .oia.Alarm alarms = 1;</code>
       */
      public java.util.List<org.opennms.integration.api.v1.proto.Model.Alarm.Builder> 
           getAlarmsBuilderList() {
        return getAlarmsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.opennms.integration.api.v1.proto.Model.Alarm, org.opennms.integration.api.v1.proto.Model.Alarm.Builder, org.opennms.integration.api.v1.proto.Model.AlarmOrBuilder> 
          getAlarmsFieldBuilder() {
        if (alarmsBuilder_ == null) {
          alarmsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.opennms.integration.api.v1.proto.Model.Alarm, org.opennms.integration.api.v1.proto.Model.Alarm.Builder, org.opennms.integration.api.v1.proto.Model.AlarmOrBuilder>(
                  alarms_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          alarms_ = null;
        }
        return alarmsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oia.AlarmsList)
    }

    // @@protoc_insertion_point(class_scope:oia.AlarmsList)
    private static final org.opennms.integration.api.v1.proto.Alarms.AlarmsList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opennms.integration.api.v1.proto.Alarms.AlarmsList();
    }

    public static org.opennms.integration.api.v1.proto.Alarms.AlarmsList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AlarmsList>
        PARSER = new com.google.protobuf.AbstractParser<AlarmsList>() {
      @java.lang.Override
      public AlarmsList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlarmsList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AlarmsList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AlarmsList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.opennms.integration.api.v1.proto.Alarms.AlarmsList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DeleteAlarmOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oia.DeleteAlarm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string reduction_key = 2;</code>
     */
    java.lang.String getReductionKey();
    /**
     * <code>string reduction_key = 2;</code>
     */
    com.google.protobuf.ByteString
        getReductionKeyBytes();
  }
  /**
   * Protobuf type {@code oia.DeleteAlarm}
   */
  public  static final class DeleteAlarm extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oia.DeleteAlarm)
      DeleteAlarmOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeleteAlarm.newBuilder() to construct.
    private DeleteAlarm(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeleteAlarm() {
      reductionKey_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeleteAlarm();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeleteAlarm(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              reductionKey_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opennms.integration.api.v1.proto.Alarms.internal_static_oia_DeleteAlarm_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opennms.integration.api.v1.proto.Alarms.internal_static_oia_DeleteAlarm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm.class, org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int REDUCTION_KEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object reductionKey_;
    /**
     * <code>string reduction_key = 2;</code>
     */
    public java.lang.String getReductionKey() {
      java.lang.Object ref = reductionKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reductionKey_ = s;
        return s;
      }
    }
    /**
     * <code>string reduction_key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReductionKeyBytes() {
      java.lang.Object ref = reductionKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reductionKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      if (!getReductionKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reductionKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (!getReductionKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reductionKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm)) {
        return super.equals(obj);
      }
      org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm other = (org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm) obj;

      if (getId()
          != other.getId()) return false;
      if (!getReductionKey()
          .equals(other.getReductionKey())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + REDUCTION_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getReductionKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oia.DeleteAlarm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oia.DeleteAlarm)
        org.opennms.integration.api.v1.proto.Alarms.DeleteAlarmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opennms.integration.api.v1.proto.Alarms.internal_static_oia_DeleteAlarm_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opennms.integration.api.v1.proto.Alarms.internal_static_oia_DeleteAlarm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm.class, org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm.Builder.class);
      }

      // Construct using org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        reductionKey_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opennms.integration.api.v1.proto.Alarms.internal_static_oia_DeleteAlarm_descriptor;
      }

      @java.lang.Override
      public org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm getDefaultInstanceForType() {
        return org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm.getDefaultInstance();
      }

      @java.lang.Override
      public org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm build() {
        org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm buildPartial() {
        org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm result = new org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm(this);
        result.id_ = id_;
        result.reductionKey_ = reductionKey_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm) {
          return mergeFrom((org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm other) {
        if (other == org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getReductionKey().isEmpty()) {
          reductionKey_ = other.reductionKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object reductionKey_ = "";
      /**
       * <code>string reduction_key = 2;</code>
       */
      public java.lang.String getReductionKey() {
        java.lang.Object ref = reductionKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reductionKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reduction_key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReductionKeyBytes() {
        java.lang.Object ref = reductionKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reductionKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reduction_key = 2;</code>
       */
      public Builder setReductionKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reductionKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reduction_key = 2;</code>
       */
      public Builder clearReductionKey() {
        
        reductionKey_ = getDefaultInstance().getReductionKey();
        onChanged();
        return this;
      }
      /**
       * <code>string reduction_key = 2;</code>
       */
      public Builder setReductionKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reductionKey_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oia.DeleteAlarm)
    }

    // @@protoc_insertion_point(class_scope:oia.DeleteAlarm)
    private static final org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm();
    }

    public static org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeleteAlarm>
        PARSER = new com.google.protobuf.AbstractParser<DeleteAlarm>() {
      @java.lang.Override
      public DeleteAlarm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeleteAlarm(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeleteAlarm> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeleteAlarm> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.opennms.integration.api.v1.proto.Alarms.DeleteAlarm getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oia_AlarmsList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oia_AlarmsList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oia_DeleteAlarm_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oia_DeleteAlarm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014alarms.proto\022\003oia\032\013model.proto\"(\n\nAlar" +
      "msList\022\032\n\006alarms\030\001 \003(\0132\n.oia.Alarm\"0\n\013De" +
      "leteAlarm\022\n\n\002id\030\001 \001(\004\022\025\n\rreduction_key\030\002" +
      " \001(\t2\275\001\n\026AlarmLifecycleListener\0224\n\023Handl" +
      "eAlarmSnapshot\022\n.oia.Empty\032\017.oia.AlarmsL" +
      "ist\"\000\0225\n\027HandleNewOrUpdatedAlarm\022\n.oia.E" +
      "mpty\032\n.oia.Alarm\"\0000\001\0226\n\022HandleDeletedAla" +
      "rm\022\n.oia.Empty\032\020.oia.DeleteAlarm\"\0000\001B-\n$" +
      "org.opennms.integration.api.v1.protoZ\005.;" +
      "oiab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.opennms.integration.api.v1.proto.Model.getDescriptor(),
        });
    internal_static_oia_AlarmsList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_oia_AlarmsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oia_AlarmsList_descriptor,
        new java.lang.String[] { "Alarms", });
    internal_static_oia_DeleteAlarm_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_oia_DeleteAlarm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oia_DeleteAlarm_descriptor,
        new java.lang.String[] { "Id", "ReductionKey", });
    org.opennms.integration.api.v1.proto.Model.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
